---
title: "rentaldata_dev connection"
---

# LIBRARIES
```{r setup, include=FALSE}
# sql connect
library(odbc)
library(DBI)
library(arrow)

# core packages
library(tidyverse)
library(dbplyr)
library(timetk)
library(tidyquant)
library(janitor)
library(lubridate)
library(zoo)

# get data
library(fredr)
library(tidycensus)


date <- today()
options(scipen = 9999)


DS_HOST     <- Sys.getenv("DS_HOST")
DS_DEV_NAME <- Sys.getenv("DS_DEV_NAME")
SQL_ID      <- Sys.getenv("SQL_ID")
SQL_PW      <- Sys.getenv("SQL_PW")


dev_conn <- dbConnect(RMariaDB::MariaDB(),
                      host     = DS_HOST,
                      dbname   = DS_DEV_NAME,
                      username = SQL_ID,
                      password = SQL_PW)

knitr::opts_chunk$set(echo = TRUE)
```

# 0.0 DATA IMPORT
```{r}
calendar_listings_cleaned <- read_parquet("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\calendar_listings_cleaned.parquet")
listings_cleaned <- read_parquet("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\listings_cleaned.parquet")

```


```{r}
dbWriteTable(conn = dev_conn, 
             name = "calendar_listings_cleaned", 
             value = calendar_listings_cleaned, 
             overwrite = T)

dbWriteTable(conn = dev_conn, 
             name = "listings_cleaned", 
             value = listings_cleaned, 
             overwrite = T)
```




## Disconnect SQL
```{r}
dbDisconnect(dev_conn)
```






