---
title: "rentedrmsprod Art Bookings"
---


# LIBRARIES
```{r setup, include=FALSE}

# sql connect
library(odbc)
library(DBI)
library(arrow)

# core packages
library(tidyverse)
library(dbplyr)
library(timetk)
library(tidyquant)
library(janitor)
library(lubridate)
library(stringi)
library(jsonlite)
library(tidyjson)
library(data.table)
library(dtplyr)

library(blastula)



date <- today()
options(scipen = 9999)

today    <- as.Date(today()+1)
today_7  <- as.Date(today()+7)
today_14 <- as.Date(today()+14)
today_30 <- as.Date(today()+30)
today_90 <- as.Date(today()+90)


config_path <- Sys.getenv("CONFIG_PATH")
config <- config::get(file = config_path)


prod_conn <-
  dbConnect(
    RMariaDB::MariaDB(),
    host     = config$prod_conn$host,
    dbname   = config$prod_conn$dbname,
    username = config$prod_conn$uid,
    password = config$prod_conn$pwd)

knitr::opts_chunk$set(echo = TRUE)
```




# --
# 1.0 SQL EXTRACTS
## pull art_listings_bookings
```{sql connection=prod_conn, output.var="art_listings_bookings_raw"}
select listings_id, booking_id, type, created_date, rate_type, rate, booking_date
from art_listings_bookings
```




# --
# 2.0 PREPARE DATA

## Preparing actual bookings only
```{r}
bookings_first_tbl <- art_listings_bookings_raw %>%
  rename(listing_id = listings_id) %>%
  filter(type == "booked" | type == "booking") %>%
  mutate(
    rate = round(rate),
    rate = ifelse(rate < 0, rate * -1, rate)
  ) 


blank_ids_fixed <- bookings_first_tbl %>%
  filter(booking_id == "" | booking_id == "0") %>%
  group_by(listing_id, created_date, rate) %>%
  unite(col = "booking_id", 
        c("listing_id", "created_date", "rate"), 
        remove = F, na.rm = F, sep = "-") %>%
  ungroup()



bookings_cleaned_tbl <- bookings_first_tbl %>%
  filter(booking_id != "" & booking_id != "0") %>%
  bind_rows(blank_ids_fixed)
```




# --
# 3.0 RATES & DAYS OUTS

## Bookings Insights
```{r}
## Use dtplyr for grouped calculations
query_bookings_dtplyr <- bookings_cleaned_tbl %>% dtplyr::lazy_dt()



bookings_prepared_dtplyr <- query_bookings_dtplyr %>%
  group_by(listing_id, booking_id) %>%
  summarise(
    total_rate = sum(rate),
    rate = mean(rate),
    created_date = min(created_date, na.rm = T),
    first_booked_date = min(booking_date, na.rm = T),
    length_of_stay = n()
  ) %>%
  ungroup() %>%
  mutate(
    days_out = difftime(first_booked_date, created_date, units = "secs"),
    days_out = round(as.numeric(days_out / 86400))
  )



# convert back to tbl
bookings_prepared_dtplyr_tbl <- as_tibble(bookings_prepared_dtplyr)
```






# --
# 4.0 BOOKINGS DAYS OUT

## Booked vs. Available
```{r}
## Use dtplyr for grouped calculations
query_dtplyr <- bookings_cleaned_tbl %>% dtplyr::lazy_dt()



bookings_time_series_dtplyr <- query_dtplyr %>%
  
  select(listing_id, booking_date) %>%
  arrange(listing_id, booking_date) %>%
  mutate(booked = 1) %>%
  
  # grouped "pad by time" (because it can't work in dtplyr) with complete & fill
  group_by(listing_id) %>%
  tidyr::complete(booking_date = seq(min(booking_date), max(booking_date), by = "1 day")) %>%
  ungroup()



# convert back to tbl
bookings_time_series_dtplyr_tbl <- as_tibble(bookings_time_series_dtplyr)
```


## Join Data
```{r}
bookings_full_tbl <- bookings_time_series_dtplyr_tbl %>%
  left_join(bookings_cleaned_tbl, by = c('listing_id', 'booking_date'))
```


## Filter by Time
```{r}
# max dates for calculation 
bookings_filter_by_time <- bookings_full_tbl %>%
  filter_by_time(
    .date_var   = booking_date, 
    .start_date = today, 
    .end_date   = today_90)


# booked_all_days_out
booked_all_days_out <- bookings_filter_by_time %>%
  dplyr::mutate(
    
    # days out booked
    days_out_7  = ifelse(between(booking_date, today, today_7), booked, NA),
    days_out_14 = ifelse(between(booking_date, today, today_14), booked, NA),
    days_out_30 = ifelse(between(booking_date, today, today_30), booked, NA),
    days_out_90 = ifelse(between(booking_date, today, today_90), booked, NA),
    
    # adr next n days
    rate_7_days  = ifelse(between(booking_date, today, today_7), rate, NA),
    rate_14_days = ifelse(between(booking_date, today, today_14), rate, NA),
    rate_30_days = ifelse(between(booking_date, today, today_30), rate, NA),
    rate_90_days = ifelse(between(booking_date, today, today_90), rate, NA)
  ) %>%
  
  # summarize by listing_id
  group_by(listing_id) %>%
  summarise(
    
    # booked next n days
    booked_7_days_out  = sum(days_out_7, na.rm = T)/7,
    booked_14_days_out = sum(days_out_14, na.rm = T)/14,
    booked_30_days_out = sum(days_out_30, na.rm = T)/30,
    booked_90_days_out = sum(days_out_90, na.rm = T)/90,
    
    # adr next n days
    booked_rate_7_days  = round(mean(rate_7_days, na.rm = T)),
    booked_rate_14_days = round(mean(rate_14_days, na.rm = T)),
    booked_rate_30_days = round(mean(rate_30_days, na.rm = T)),
    booked_rate_90_days = round(mean(rate_90_days, na.rm = T))
  ) %>%
  ungroup() %>%
  mutate_all(~replace(., is.na(.), 0))
```




# --
# 5.0 SAVE bookings_prepared WITH DATES

## Save to db
```{r}
ds_conn <- 
  dbConnect(
    RMariaDB::MariaDB(),
    host     = config$ds_conn$host,
    dbname   = config$ds_conn$dbname,
    username = config$ds_conn$uid,
    password = config$ds_conn$pwd)


## handy little function
dbWriteTableMySQLFast<- function(conn, df, tbl_name) {
  dbRemoveTable(conn, tbl_name, fail_if_missing = FALSE)
  dbCreateTable(conn, tbl_name, fields = df)
  
  f <- tempfile()
  write_csv(df, file = f, na = "NULL")
  
  dbWriteTable(conn, tbl_name, f, append = TRUE)

  unlink(f)
}


# upload
dbWriteTableMySQLFast(
  conn     = ds_conn, 
  df       = bookings_prepared_dtplyr_tbl, 
  tbl_name = "00_art_listings_bookings"
)

DBI::dbDisconnect(ds_conn)
```


## Save as parquet
```{r}
# live file in scheduled/00_data folder
write_parquet(bookings_prepared_dtplyr_tbl, "C:\\Users\\DavidStephens\\Desktop\\Github\\scheduled\\00_data\\art_listings_bookings.parquet")


# live file for shiny in art_replica/shiny folder
write_parquet(bookings_prepared_dtplyr_tbl, "C:\\Users\\DavidStephens\\Desktop\\Github\\artr_replica\\shiny\\art_listings_bookings.parquet")



# time-stamped archive file
write_parquet(bookings_prepared_dtplyr_tbl, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\scheduled\\00_data\\archive\\{date}_art_listings_bookings.parquet"))
```




# --
# 6.0 SAVE booked_all_days_out SUMMARIZED BY listing_id

## Save to db
```{r}
ds_conn <- 
  dbConnect(
    RMariaDB::MariaDB(),
    host     = config$ds_conn$host,
    dbname   = config$ds_conn$dbname,
    username = config$ds_conn$uid,
    password = config$ds_conn$pwd)


## handy little function
dbWriteTableMySQLFast<- function(conn, df, tbl_name) {
  dbRemoveTable(conn, tbl_name, fail_if_missing = FALSE)
  dbCreateTable(conn, tbl_name, fields = df)
  
  f <- tempfile()
  write_csv(df, file = f, na = "NULL")
  
  dbWriteTable(conn, tbl_name, f, append = TRUE)

  unlink(f)
}


# upload
dbWriteTableMySQLFast(
  conn     = ds_conn, 
  df       = booked_all_days_out, 
  tbl_name = "00_booked_days_out"
)
```


```{r}
DBI::dbDisconnect(prod_conn)
DBI::dbDisconnect(ds_conn)
```




## Save 
```{r}
# live file in scheduled/00_data folder
write_rds(booked_all_days_out, "C:\\Users\\DavidStephens\\Desktop\\Github\\scheduled\\00_data\\booked_days_out.rds")


# live file for shiny in art_replica/shiny folder
write_rds(booked_all_days_out, "C:\\Users\\DavidStephens\\Desktop\\Github\\artr_replica\\shiny\\booked_days_out.rds")



# time-stamped archive file
write_rds(booked_all_days_out, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\scheduled\\00_data\\archive\\{date}_booked_days_out.rds"))
```




# --
# 7.0 EMAIL NOTIFICATION
```{r}

date_time <- add_readable_time()

body_text <- 
  md(str_glue(
    
"
Good news!

The **rentedrmsprod: Art Listings Bookings** script ran successfully on {date_time}.

"))


footer_text <- md("sent via the [blastula](https://rstudio.github.io/blastula) R package")



email <- compose_email(
  body = body_text,
  footer = footer_text
)


# send the email
email %>%
  smtp_send(
    from = "dstephens@tnsinc.com",
    to = "dstephens@tnsinc.com", 
    subject = str_glue("Art Listings Bookings & Booked Days Out"),
    credentials = creds_file(file = "C:\\Users\\DavidStephens\\Desktop\\Github\\scheduled\\gmail_creds")
  )
```










