---
title: "data(.table) wrangling"
subtitle: "https://github.com/rstudio/cheatsheets/blob/main/datatable.pdf"
---


# LIBRARIES
```{r setup, include=FALSE}
# sql connect
library(odbc)
library(DBI)
library(arrow)

# core packages
library(tidyverse)
library(data.table)
library(dbplyr)
library(timetk)
library(tidyquant)
library(janitor)
library(lubridate)
library(zoo)

# get data
library(fredr)
library(tidycensus)


date <- today()
options(scipen = 9999)

knitr::opts_chunk$set(echo = TRUE)
```


# 0.0 DATA IMPORT
```{r}
listings_raw <- read_parquet(str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\combined_listings_raw.parquet"))
calendar_raw <- read_parquet(str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\combined_calendar_raw.parquet"))
active_raw   <- read_parquet(str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\combined_active_raw.parquet"))


# set as data.table
setDT(listings_raw)
setDT(calendar_raw)
setDT(active_raw)
```



data.table basics
DT[i, j, by]
  i = row-wise?
  j = column-wise operations?
  by = grouped by what?



========================
# 1.0 CALENDAR_LISTINGS
## left_join on full dataset
```{r}
# left_join
calendar_listings_raw <- calendar_raw[listings_raw, on = .(listing_id = listing_id)][active_raw, on = .(listing_id = listing_id), nomatch=0]


## na.omit
calendar_listings_cleaned <- na.omit(calendar_listings_raw, "date")


# number of unique
uniqueN(calendar_listings_cleaned, by = "listing_id")


# set order
setorderv(calendar_listings_cleaned, c("listing_id", "date"))
```


## Save calendar_listings_cleaned
```{r}
# live-file
write_parquet(calendar_listings_cleaned, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\calendar_listings_cleaned.parquet"))

# archive
write_parquet(calendar_listings_cleaned, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\archive\\{date}_calendar_listings_cleaned.parquet"))
```




# 2.0 LISTINGS_CLEANED
## Aggregation functions & cleaning
```{r}
# create adr column grouped by listing_id
calendar_listings_aggregated <- calendar_listings_cleaned[, adr := round(mean(rate), 0), by = .(listing_id)]


# drop columns
calendar_listings_aggregated[, ':=' (date = NULL, rate = NULL, available = NULL)]


# select first row of each listing_id
listings_cleaned <- calendar_listings_aggregated[, .SD[1], by = listing_id]
```


## Save listings_cleaned
```{r}
# live file
write_parquet(listings_cleaned, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\listings_cleaned.parquet"))

# archive
write_parquet(listings_cleaned, str_glue("C:\\Users\\DavidStephens\\Desktop\\Github\\forecasting_framework\\00_data\\archive\\{date}_listings_cleaned.parquet"))
```

























# data.table functions
x.x Not Run
```{r, eval=FALSE}
# number of rows by group
listings_aggregated[, .N, by = listing_id]


# select columns from listing_id to longitude
listings_aggregated[, .SD, .SDcols = listing_id:longitude]
```











