---
title: "rentedrmsprod data pull"
---


# LIBRARIES
```{r setup, include=FALSE}
# sql connect
library(odbc)
library(DBI)
library(arrow)

# core packages
library(tidyverse)
library(dbplyr)
library(timetk)
library(tidyquant)
library(janitor)
library(lubridate)
library(stringi)
library(jsonlite)
library(tidyjson)
library(data.table)

# get data
library(fredr)
library(tidycensus)


date <- today()
options(scipen = 9999)


PROD_HOST    <- Sys.getenv("PROD_HOST")
PROD_DB_NAME <- Sys.getenv("PROD_DB_NAME")
PROD_ID      <- Sys.getenv("PROD_ID")
PROD_PW      <- Sys.getenv("PROD_PW")

prod_conn <- dbConnect(RMariaDB::MariaDB(),
                        host     = PROD_HOST,
                        dbname   = PROD_DB_NAME,
                        username = PROD_ID,
                        password = PROD_PW)

knitr::opts_chunk$set(echo = TRUE)
```




# 1.0 SQL EXTRACTS
## pull art_listings
```{sql connection=prod_conn, output.var="prod_art_listings"}
select cast(id as CHAR), cast(accounts_id as CHAR), cast(listing_name as CHAR), cast(details as CHAR)
from art_listings
limit 50
```




```{r}
prod_art_listings_unnested <- prod_art_listings %>%
  rename(
    id           = `cast(id as CHAR)`,
    account_id   = `cast(accounts_id as CHAR)`,
    listing_name = `cast(listing_name as CHAR)`,
    details      = `cast(details as CHAR)`
  ) %>%
  select(-listing_name) %>%
  rowwise() %>%
  mutate(details_extract = list(fromJSON(details))) %>%
  ungroup() %>%
  unnest_wider(details_extract)

```


## Disconnect SQL
```{r}
dbDisconnect(prod_conn)
```



















